export const memberSelect = {
  id: true,
  email: true,
  firstName: true,
  lastName: true,
  preferredName: true,
  avatar: true,
  shirtSize: true,
  dob: true,
  cantonEmail: true,
  position: true,
  isAdmin: true,
  major: true,
  membershipStanding: true,
  cantonCardId: true,
  gpa: true,
  phoneNumber: true,
  medicalLevel: true,
  housingType: true,
  buildingId: true,
  building: {
    select: {
      id: true,
      name: true,
      address: true,
    },
  },
  roomNumber: true,
  homeAddress: true,
  localAddress: true,
  createdAt: true,
  updatedAt: true,
  emailVerified: true,
  image: true,
  name: true,
} as const;
